DROP TABLE  REAP_FACILITY.CONFIG;

CREATE TABLE REAP_FACILITY.CONFIG
(   
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    SYSTEM_CODE VARCHAR(100),
    PROFILE VARCHAR(100),
    LABEL VARCHAR(100),
    NAME VARCHAR(1024),
    VALUE VARCHAR(1024),
    REMARK VARCHAR(500)
);
DROP TABLE  REAP_FACILITY.ROUTE;

CREATE TABLE REAP_FACILITY.ROUTE
(
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    PATH VARCHAR(100) NOT NULL UNIQUE,
    SYSTEM_CODE VARCHAR(100) NOT NULL,
    URL VARCHAR(1024),
    STRIP_PREFIX VARCHAR(100)
);

DROP TABLE  REAP_FACILITY.APPLICATION;

CREATE TABLE REAP_FACILITY.APPLICATION
(
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    SYSTEM_CODE VARCHAR(100) NOT NULL UNIQUE,
    OWNER VARCHAR(100) NOT NULL,
    CREATE_TIME TIMESTAMP,
    REMARK VARCHAR(500)
);

DROP TABLE  REAP_PORTAL.USER_SETTING;

CREATE TABLE REAP_PORTAL.USER_SETTING(
ID VARCHAR(50) NOT NULL PRIMARY KEY,
USER_ID VARCHAR(50) NOT NULL,
HOME_FUNCTION_CODE VARCHAR(50)
);
    
DROP TABLE  REAP_PORTAL.USER_FAV_FUNCTION;

CREATE TABLE REAP_PORTAL.USER_FAV_FUNCTION(
ID VARCHAR(50) NOT NULL PRIMARY KEY,
USER_SETTING_ID VARCHAR(50) NOT NULL,
FUNCTION_CODE VARCHAR(50) NOT NULL
);

DROP TABLE  REAP_PORTAL.USER_SETTING_FAV_FUNCTIONS;

CREATE TABLE REAP_PORTAL.USER_SETTING_FAV_FUNCTIONS(
 USER_SETTING_ID VARCHAR(50),
 FAV_FUNCTIONS_ID VARCHAR(50)
);

DROP TABLE  REAP_PORTAL.MENU;

CREATE TABLE REAP_PORTAL.MENU(
ID VARCHAR(50) NOT NULL PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
PARENT_ID VARCHAR(50),
LEVEL INTEGER NOT NULL,
SEQUENCE INTEGER NOT NULL,
LEAF VARCHAR(1),
FUNCTION_CODE VARCHAR(50),
REMARK VARCHAR(500),
CREATE_TIME TIMESTAMP
);

DROP TABLE  REAP_RBAC.USER;
CREATE TABLE REAP_RBAC.USER
(
   ID VARCHAR(50) NOT NULL PRIMARY KEY,
   USERNAME VARCHAR(100) NOT NULL,
   NAME VARCHAR(100) NOT NULL,
   PASSWORD VARCHAR(100) NOT NULL,
   EMAIL VARCHAR(200) NOT NULL,
   PHONE_NO VARCHAR(20) NOT NULL,
   CREATE_TIME TIMESTAMP,
   GENDER CHAR(1),
   ORG_ID VARCHAR(50),
   REMARK VARCHAR(500)
);
DROP TABLE  REAP_RBAC.ORG;
CREATE TABLE REAP_RBAC.ORG
(
   ID VARCHAR(50) NOT NULL PRIMARY KEY,
   NAME VARCHAR(100) NOT NULL,
   CODE VARCHAR(50) NOT NULL,
   BUSINESS_TYPE_ID VARCHAR(50),
   CREATE_TIME TIMESTAMP,
   PARENT_ID VARCHAR(50),
   REMARK VARCHAR(500),
   LEAF CHAR(1)
);
DROP TABLE  REAP_RBAC.ROLE;
CREATE TABLE REAP_RBAC.ROLE
(
   ID VARCHAR(50) NOT NULL PRIMARY KEY,
   CREATE_TIME TIMESTAMP,
   NAME VARCHAR(100) NOT NULL,
   REMARK VARCHAR(500)
);
DROP TABLE  REAP_RBAC.USER_ROLE;
CREATE TABLE REAP_RBAC.USER_ROLE
(
   USER_ID VARCHAR(50) NOT NULL,
   ROLE_ID VARCHAR(50) NOT NULL,
   PRIMARY KEY (USER_ID,ROLE_ID)
);
DROP TABLE  REAP_RBAC.FUNCTION;
CREATE TABLE REAP_RBAC.FUNCTION
(
   ID VARCHAR(50) NOT NULL PRIMARY KEY,
   SERVICE_ID VARCHAR(200) NOT NULL,
   CODE VARCHAR(50) NOT NULL,
   NAME VARCHAR(100) NOT NULL,
   TYPE CHAR(1) NOT NULL,
   ACTION VARCHAR(500) DEFAULT NULL,
   REMARK VARCHAR(500) DEFAULT NULL
);

DROP TABLE  REAP_RBAC.ROLE_FUNCTION;

CREATE TABLE REAP_RBAC.ROLE_FUNCTION(
 ROLE_ID VARCHAR(50),
 FUNCTION_ID VARCHAR(50)
);

DROP TABLE  REAP_RBAC.BUSINESS_TYPE;

CREATE TABLE REAP_RBAC.BUSINESS_TYPE
(
  ID VARCHAR(100) NOT NULL PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL UNIQUE,
  CREATED_TIME TIMESTAMP,
  REMARK VARCHAR(100)
);

DROP TABLE  REAP_RBAC.BUSINESS_TYPE_FUNCTION;

CREATE TABLE REAP_RBAC.BUSINESS_TYPE_FUNCTION (
  BUSINESS_TYPE_ID VARCHAR(50),
  FUNCTION_ID VARCHAR(50)
)