DROP TABLE IF EXISTS CONFIG;

CREATE TABLE CONFIG
(   
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    SYSTEM_CODE VARCHAR(100),
    PROFILE VARCHAR(100),
    LABEL VARCHAR(100),
    NAME VARCHAR(1024),
    VALUE VARCHAR(1024),
    REMARK VARCHAR(500)
);
DROP TABLE IF EXISTS ROUTE;

CREATE TABLE ROUTE
(
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    PATH VARCHAR(100) NOT NULL UNIQUE,
    SYSTEM_CODE VARCHAR(100) NOT NULL,
    URL VARCHAR(1024),
    STRIP_PREFIX VARCHAR(100)
);

DROP TABLE IF EXISTS APPLICATION;

CREATE TABLE APPLICATION
(
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    SYSTEM_CODE VARCHAR(100) NOT NULL UNIQUE,
    OWNER VARCHAR(100) NOT NULL,
    CREATE_TIME TIMESTAMP,
    REMARK VARCHAR(500)
);

DROP TABLE IF EXISTS USER_SETTING;

CREATE TABLE USER_SETTING(
ID VARCHAR(50) NOT NULL PRIMARY KEY,
USER_ID VARCHAR(50) NOT NULL,
HOME_FUNCTION_CODE VARCHAR(50)
);
    
DROP TABLE IF EXISTS USER_FAV_FUNCTION;

CREATE TABLE USER_FAV_FUNCTION(
ID VARCHAR(50) NOT NULL PRIMARY KEY,
USER_SETTING_ID VARCHAR(50) NOT NULL,
FUNCTION_CODE VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS USER_SETTING_FAV_FUNCTIONS;

CREATE TABLE USER_SETTING_FAV_FUNCTIONS(
 USER_SETTING_ID VARCHAR(50),
 FAV_FUNCTIONS_ID VARCHAR(50)
);

DROP TABLE IF EXISTS MENU;

CREATE TABLE MENU(
ID VARCHAR(50) NOT NULL PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
PARENT_ID VARCHAR(50),
LEVEL INTEGER NOT NULL,
SEQUENCE INTEGER NOT NULL,
LEAF VARCHAR(1),
FUNCTION_CODE VARCHAR(50),
REMARK VARCHAR(500),
CREATE_TIME TIMESTAMP
);

DROP TABLE IF EXISTS USER;
CREATE TABLE USER
(
   ID VARCHAR(50) NOT NULL PRIMARY KEY,
   USERNAME VARCHAR(100) NOT NULL,
   NAME VARCHAR(100) NOT NULL,
   PASSWORD VARCHAR(100) NOT NULL,
   EMAIL VARCHAR(200) NOT NULL,
   PHONE_NO VARCHAR(20) NOT NULL,
   CREATE_TIME TIMESTAMP,
   GENDER CHAR(1),
   ORG_ID VARCHAR(50),
   REMARK VARCHAR(500)
);
DROP TABLE IF EXISTS ORG;
CREATE TABLE ORG
(
   ID VARCHAR(50) NOT NULL PRIMARY KEY,
   NAME VARCHAR(100) NOT NULL,
   CODE VARCHAR(50) NOT NULL,
   CREATE_TIME TIMESTAMP,
   PARENT_ID VARCHAR(50),
   REMARK VARCHAR(500),
   LEAF CHAR(1)
);
DROP TABLE IF EXISTS ROLE;
CREATE TABLE ROLE
(
   ID VARCHAR(50) NOT NULL PRIMARY KEY,
   CREATE_TIME TIMESTAMP,
   NAME VARCHAR(100) NOT NULL,
   REMARK VARCHAR(500)
);
DROP TABLE IF EXISTS USER_ROLE;
CREATE TABLE USER_ROLE
(
   USER_ID VARCHAR(50) NOT NULL,
   ROLE_ID VARCHAR(50) NOT NULL,
   PRIMARY KEY (USER_ID,ROLE_ID)
);
DROP TABLE IF EXISTS FUNCTION;
CREATE TABLE FUNCTION
(
   ID VARCHAR(50) NOT NULL PRIMARY KEY,
   SERVICE_ID VARCHAR(200) NOT NULL,
   CODE VARCHAR(50) NOT NULL,
   NAME VARCHAR(100) NOT NULL,
   TYPE CHAR(1) NOT NULL,
   ACTION VARCHAR(500) DEFAULT NULL,
   REMARK VARCHAR(500) DEFAULT NULL
);

DROP TABLE IF EXISTS ROLE_FUNCTION;

CREATE TABLE ROLE_FUNCTION(
 ROLE_ID VARCHAR(50),
 FUNCTION_ID VARCHAR(50)
);
